# Generated by Django 6.0.6 on 2026-07-04 23:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Listing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_id', models.CharField(db_index=True, max_length=64)),
                ('title', models.CharField(blank=True, default='', max_length=255)),
                ('description', models.TextField(blank=True, default='')),
                ('language', models.CharField(blank=True, db_index=True, default='', max_length=10)),
                ('currency', models.CharField(default='EUR', max_length=8)),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('price_base', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('images', models.JSONField(blank=True, default=list, null=True)),
                ('location_id', models.CharField(blank=True, default='', max_length=64)),
                ('location_label', models.CharField(blank=True, default='', max_length=255)),
                ('geohash', models.CharField(blank=True, db_index=True, default='', max_length=12)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Moderation'), ('published', 'Published'), ('paused', 'Paused'), ('expired', 'Expired'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20)),
                ('moderation_status', models.CharField(choices=[('pending', 'Pending Review'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('needs_review', 'Needs Manual Review')], default='pending', max_length=20)),
                ('moderation_note', models.TextField(blank=True, default='')),
                ('auto_republish', models.BooleanField(default=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('expiry_notification_sent', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True)),
                ('features', models.JSONField(blank=True, default=list, null=True)),
                ('features_title', models.JSONField(blank=True, default=list, null=True)),
                ('features_badges', models.JSONField(blank=True, default=list, null=True)),
                ('features_search', models.JSONField(blank=True, default=dict, null=True)),
                ('features_draft', models.JSONField(blank=True, default=dict, null=True)),
                ('title_draft', models.CharField(blank=True, default='', max_length=255)),
                ('description_draft', models.TextField(blank=True, default='')),
                ('price_draft', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('images_draft', models.JSONField(blank=True, default=list, null=True)),
                ('location_id_draft', models.CharField(blank=True, default='', max_length=64)),
                ('location_label_draft', models.CharField(blank=True, default='', max_length=255)),
                ('geohash_draft', models.CharField(blank=True, default='', max_length=12)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Favorite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listing_favorites', to=settings.AUTH_USER_MODEL)),
                ('listing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='favorites', to='listings.listing')),
            ],
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['owner', 'status'], name='listing_owner_status_idx'),
        ),
        migrations.AddIndex(
            model_name='listing',
            index=models.Index(fields=['category_id', 'status'], name='listing_cat_status_idx'),
        ),
        migrations.AddIndex(
            model_name='favorite',
            index=models.Index(fields=['user', '-created_at'], name='fav_user_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='favorite',
            constraint=models.UniqueConstraint(fields=('user', 'listing'), name='uniq_user_listing_fav'),
        ),
    ]
