# Generated by Django 6.0.6 on 2026-07-06 04:41

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='countable',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='listing',
            name='stock_quantity',
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AddConstraint(
            model_name='listing',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('countable', True), ('stock_quantity__gte', 0), ('stock_quantity__isnull', False)), models.Q(('countable', False), ('stock_quantity__isnull', True)), _connector='OR'), name='listing_stock_invariant_chk'),
        ),
    ]
