# Generated by Django 6.0.6 on 2026-07-07 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_listing_countable_stock_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='currency',
            field=models.CharField(default='USD', max_length=8),
        ),
    ]
