# Generated by Django 6.0.7 on 2026-08-21 09:52

#
# Adds the ``blocked`` lifecycle state (moderation takedown of a live
# listing). Choices-only AlterField: no column type change, no data rewrite,
# no existing row affected — every current status stays valid.

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0004_listing_lat_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('pending', 'Pending Moderation'), ('published', 'Published'), ('paused', 'Paused'), ('expired', 'Expired'), ('sold', 'Sold'), ('rejected', 'Rejected'), ('blocked', 'Blocked (moderation takedown)'), ('archived', 'Archived')], db_index=True, default='draft', max_length=20),
        ),
    ]
