# Generated by Django 6.0.8 on 2026-09-03 02:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0007_listing_view_count_listingview'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listing',
            name='category_id',
            field=models.CharField(db_index=True, max_length=64, validators=[django.core.validators.RegexValidator(code='invalid_category_id', message='A category id is an opaque id, not a path. Got a value containing a separator — a slash-joined category PATH belongs in the search ?category= filter, not in category_id.', regex='\\A[A-Za-z0-9][A-Za-z0-9_-]*\\Z')]),
        ),
    ]
